--- 
abstract: Yet Another High Performance Web Crawler Framework
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Gungho
no_index: 
  directory: 
    - inc
    - t
recommends: 
  POE: 0
  POE::Component::Client::HTTP: 0
  POE::Component::Client::Keepalive: 0
requires: 
  Class::Accessor::Fast: 0
  Class::C3: 0
  Class::Inspector: 0
  Config::Any: 0
  UNIVERSAL::require: 0
version: 0.01
