--- 
abstract: Yet Another High Performance Web Crawler Framework
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Gungho
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Best: 0
  Class::C3: 0.16
  Class::C3::XS: 0.02
  DB_File: 0
  Danga::Socket::Callback: 0
  Data::Throttler: 0
  HTTP::Headers::Util: 0
  HTTP::Parser: 0
  HTTP::Status: 0
  IO::Async::Buffer: 0
  IO::Socket::INET: 0
  MIME::Base64: 0
  Net::DNS: 0
  POE: 0
  POE::Component::Client::DNS: 0
  POE::Component::Client::HTTP: 0
  POE::Component::Client::Keepalive: 0
  Time::HiRes: 0
  URI: 0
  WWW::RobotRules::Parser: 0
  YAML: 0
requires: 
  Best: 0
  Class::Accessor::Fast: 0
  Class::C3: 0
  Class::Inspector: 0
  Config::Any: 0
  Data::Dump: 0
  Exception::Class: 0
  FindBin: 0
  Getopt::Long: 0
  Path::Class: 0
  Pod::Usage: 0
  Regexp::Common: 0
  Storable: 0
  UNIVERSAL::isa: 0
  UNIVERSAL::require: 0
  perl: 5.8.0
tests: t/01_load.t t/02_config.t t/03_live/perl.t t/03_live/twitter.t t/99_kwalitee.t t/99_pod-coverage.t t/99_pod.t t/engine/danga-socket/01_load.t t/engine/danga-socket/04_dns.t t/engine/io-async/01_load.t t/engine/io-async/04_dns.t t/engine/poe/01_load.t t/engine/poe/04_dns.t t/engine/poe/05_dns_params.t
version: 0.08005
